DROP TABLE IF EXISTS T_EVENT;
CREATE TABLE T_EVENT (
    EVENT_ID VARCHAR(32) NOT NULL,
    TITLE VARCHAR(16) NOT NULL,
    DESCRIPTION VARCHAR(256) NOT NULL,
    UPDATE_USER VARCHAR(64) NOT NULL,
    UPDATE_TSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EVENT_ID)
);

DROP TABLE IF EXISTS T_PROPOSED_DATETIME;
CREATE TABLE T_PROPOSED_DATETIME (
    EVENT_ID VARCHAR(32) NOT NULL,
    PROPOSED_DATETIME VARCHAR(32) ,
    UPDATE_USER VARCHAR(64) NOT NULL,
    UPDATE_TSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EVENT_ID, PROPOSED_DATETIME)
);

DROP TABLE IF EXISTS T_ANSWER;
CREATE TABLE T_ANSWER (
    EVENT_ID VARCHAR(32) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    PROPOSED_DATETIME VARCHAR(32) ,
    ANSWER VARCHAR(1) NOT NULL,
    UPDATE_USER VARCHAR(64) NOT NULL,
    UPDATE_TSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EVENT_ID, USER_NAME, PROPOSED_DATETIME)
);

